FROM docker.io/debian:trixie AS debian

RUN apt-get update -y && \
    apt-get install python3-openssl -y && \
    apt-get install pagekite -y 

RUN mkdir /etc/pagekite

WORKDIR /etc/pagekite

CMD ["/bin/bash", "-c", "pagekite"]

#ENTRYPOINT ["tail", "-f", "/dev/null"]